public class SelectRestraExt {

    public SelectRestraExt(){
        AreaList = new List<String>();
        AreaList.add('asdqwe');
        AreaList.add('asdf');
    }

    public PageReference UpdateRestra() {
        return null;
    }


    public String rList { get; set; }

    public String selectedR { get; set; }

    public List<String> AreaList { get; set; }

    public String selectedArea { get; set; }

    public String getFindRestra() {
        return null;
    }

}